project_id = "gjbuoyxwujpbaprcrnmg"

[functions.replay-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false