// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_services_default = defineTool({
  name: "list_services",
  title: "List services",
  description: "List Plan B Asia's active advisory services (visas, relocation, wellness, expeditions, etc). Optionally filter by category or locale.",
  inputSchema: {
    category: z.string().optional().describe("Optional category filter, e.g. 'visa', 'wellness', 'expedition'."),
    locale: z.enum(["en", "tr", "all"]).optional().describe("Restrict to services visible on the EN, TR, or all sites. Defaults to 'all'."),
    limit: z.number().int().min(1).max(100).optional().describe("Max services to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, locale, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("services").select(
      "id,title,slug,category,short_description,price,currency,delivery_time_days,visible_on,is_featured"
    ).eq("is_active", true).order("order_index", { ascending: true }).limit(limit ?? 50);
    if (category) q = q.eq("category", category.toLowerCase());
    if (locale && locale !== "all") q = q.in("visible_on", [locale, "all"]);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_service_default = defineTool2({
  name: "get_service",
  title: "Get service",
  description: "Fetch the full details of a single Plan B Asia service by its slug (e.g. 'dtv-visa', 'thailand-elite'). Includes description, features, FAQ, price, and delivery time.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Service slug (lowercase, hyphenated).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("services").select("*").eq("slug", slug.toLowerCase()).eq("is_active", true).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: `No active service found for slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { service: data }
    };
  }
});

// src/lib/mcp/tools/submit-lead.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_lead_default = defineTool3({
  name: "submit_lead",
  title: "Submit lead inquiry",
  description: "Submit a new advisory inquiry to Plan B Asia. Use when the user wants to start a conversation with the strategic advisory team about relocation, visas, or wellness. Returns a lead id.",
  inputSchema: {
    name: z3.string().trim().min(1).max(200).describe("Full name of the prospective client."),
    email: z3.string().trim().toLowerCase().email().max(200),
    whatsapp: z3.string().trim().max(50).optional().describe("Optional WhatsApp number in E.164 format."),
    intent: z3.string().trim().max(2e3).optional().describe("What the client is looking for (short free text)."),
    service_slug: z3.string().trim().optional().describe("Optional slug of the service the lead is interested in."),
    language: z3.enum(["en", "tr"]).optional().describe("Preferred contact language.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, whatsapp, intent, service_slug, language }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let service_id = null;
    if (service_slug) {
      const { data: svc } = await supabase.from("services").select("id").eq("slug", service_slug.toLowerCase()).maybeSingle();
      service_id = svc?.id ?? null;
    }
    const { data, error } = await supabase.from("leads").insert({
      name,
      email,
      customer_whatsapp: whatsapp ?? null,
      intent: intent ?? null,
      service_id,
      language: language ?? "en",
      created_from: "mcp",
      entry_point: "mcp",
      source_site: "mcp"
    }).select("id").single();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead created: ${data.id}` }],
      structuredContent: { lead_id: data.id }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "plan-b-asia-mcp",
  title: "Plan B Asia MCP",
  version: "0.1.0",
  instructions: "Tools for Plan B Asia / The Sovereign OS. Use `list_services` and `get_service` to browse advisory offerings (visas, relocation, wellness, expeditions). Use `submit_lead` to open a new advisory inquiry on the user's behalf.",
  tools: [list_services_default, get_service_default, submit_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
